Repository DeveloperAcademy-POSTECH/2024-MacC-M06-DoRise, pull requests merged in 2024-11, with the labels that each got.

#44 [FEAT/#43] 코드 컨벤션 적용+익스텐션 예시 추가(아직 반영x)+파일 삭제+오류 수정+모델 추가
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/Helper/Helper+Color.swift
  DoBday/DoBday/Helper/Helper+Fonts.swift
  DoBday/DoBday/Model/BDayAndGiftCombination.swift
  DoBday/DoBday/Model/Bday.swift
  DoBday/DoBday/Model/BdayGift.swift
  DoBday/DoBday/Model/BdayTag.swift
  DoBday/DoBday/Model/GiftStatus.swift
  DoBday/DoBday/Model/LunarToSolarConversionView.swift
  DoBday/DoBday/View/CalendarView.swift
  DoBday/DoBday/View/EditBdayView.swift
  DoBday/DoBday/View/LocalNotificationManager.swift
  DoBday/DoBday/View/SaveBdayView.swift
Labels: 🐣 FEAT

#51 [PR/#50] 오타 수정, 폰트 이름에 bday_ 추가
  DoBday/DoBday/Helper/Helper+Fonts.swift
Labels: 🔧 Fix

#65 [PR/#61] 기본 태그 추가(가족/친구)/이미지 타입에서 데이터 타입으로 변환
  DoBday/.DS_Store
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/.DS_Store
  DoBday/DoBday/App/DoBdayApp.swift
  DoBday/DoBday/Model/Bday.swift
  DoBday/DoBday/Model/BdayTag.swift
  DoBday/DoBday/Model/MockData.swift
  DoBday/DoBday/View/BdayTextView.swift
  DoBday/DoBday/View/CalendarView.swift
  DoBday/DoBday/View/PersonDetailView.swift
  DoBday/DoBday/View/SaveBdayView.swift
  DoBday/DoBday/View/SetTagView.swift
  DoBday/DoBday/View/UpComingBdayCardView.swift
  DoBday/DoBday/View/UpComingBdayView.swift
Labels: 🔧 Fix

#68 [PR/#66] DetailProfileView수정/PersonView 추가
  DoBday/.DS_Store
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/View/CalendarView.swift
  DoBday/DoBday/View/PersonDetailView.swift
  DoBday/DoBday/View/PersonListView.swift
  DoBday/DoBday/View/SaveBdayView.swift
Labels: 🔧 Fix

#67 [FEAT/#64] SaveGiftView, GiveAndTakeView 구현
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/App/DoBdayApp.swift
  DoBday/DoBday/View/GiveAndTakeView.swift
  DoBday/DoBday/View/PersonDetailView.swift
  DoBday/DoBday/View/SaveGiftView.swift
Labels: 🐣 FEAT, 🎨 Design

#76 [PR/#71] 리펙토링 작업(SaveBdayView/SetTagView/SetDateView/PersonDetailView)
  DoBday/.DS_Store
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/View/PersonDetailView.swift
  DoBday/DoBday/View/PersonDetailView/PersonDetailView.swift
  DoBday/DoBday/View/PersonDetailView/ShowingPresentForGiveAndTakeView.swift
  DoBday/DoBday/View/PersonDetailView/ShowingPresentForGivingToYouView.swift
  DoBday/DoBday/View/PersonDetailView/ShowingProfileOfPersonView.swift
  DoBday/DoBday/View/PersonDetailView/ShowingTasteCollageView.swift
  DoBday/DoBday/View/SaveBdayView.swift
  DoBday/DoBday/View/SaveBdayView/ButtonForCheckingIsLunar.swift
  DoBday/DoBday/View/SaveBdayView/ButtonForCheckingTheDate.swift
  DoBday/DoBday/View/SaveBdayView/ButtonForMovingToSetTagView.swift
  DoBday/DoBday/View/SaveBdayView/ChooseAlarmFrequencyView.swift
  DoBday/DoBday/View/SaveBdayView/ChooseTagsInSaveBdayView.swift
  DoBday/DoBday/View/SaveBdayView/HeaderForSaveBdayView.swift
  DoBday/DoBday/View/SaveBdayView/PhotoPickerForSaveBdayView.swift
  DoBday/DoBday/View/SaveBdayView/SaveBdayView.swift
  DoBday/DoBday/View/SaveBdayView/SetAlarmInSaveBdayView.swift
  DoBday/DoBday/View/SaveBdayView/SetBirthForSaveBdayView.swift
  DoBday/DoBday/View/SaveBdayView/SetNameForSaveBdayView.swift
  DoBday/DoBday/View/SaveBdayView/ShowingBdayTagOfSaveBdayView.swift
  DoBday/DoBday/View/SetDateView.swift
  DoBday/DoBday/View/SetDateView/ButtonOfShowingSheetForSettingDateView.swift
  DoBday/DoBday/View/SetDateView/DatePickerOfSetDateView.swift
  DoBday/DoBday/View/SetDateView/IsLunarDateTextView.swift
  DoBday/DoBday/View/SetDateView/SetDateView.swift
  DoBday/DoBday/View/SetTagView.swift
  DoBday/DoBday/View/SetTagView/ButtonOfSavingBdayTagView.swift
  DoBday/DoBday/View/SetTagView/ChoosingColorOfTagView.swift
  DoBday/DoBday/View/SetTagView/SetTagView.swift
  DoBday/DoBday/View/SetTagView/TextFieldForTagView.swift
Labels: 🔧 Fix

#80 [PR/#79] UpcomingBdayCardView 리팩토링 및 버그 수정
  DoBday/.DS_Store
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/View/CalendarView/CalendarView.swift
  DoBday/DoBday/View/CalendarView/CardListView.swift
  DoBday/DoBday/View/Component/PhotoCircle.swift
  DoBday/DoBday/View/Component/PhotoRoundedRect.swift
  DoBday/DoBday/View/GiveAndTakeView/GiftCardView.swift
  DoBday/DoBday/View/PersonDetailView/PersonDetailView.swift
  DoBday/DoBday/View/PersonDetailView/ShowingPresentForGiveAndTakeView.swift
  DoBday/DoBday/View/UpComingBdayCardView.swift
Labels: 🔧 Fix
