Repository DeveloperAcademy-POSTECH/2024-MacC-M06-DoRise, pull requests merged in 2024-10, with the labels that each got.

#2 [Setting/#1] 기초 세팅 작업
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  DoBday/DoBday.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  DoBday/DoBday/App/DoBdayApp.swift
  DoBday/DoBday/Helper/Helper+Fonts.swift
  DoBday/DoBday/Model/Model.swift
  DoBday/DoBday/Preview Content/Preview Assets.xcassets/Contents.json
  DoBday/DoBday/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  DoBday/DoBday/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  DoBday/DoBday/Resource/Assets.xcassets/Contents.json
  DoBday/DoBday/VIewModel/ViewModel.swift
  DoBday/DoBday/View/Component/Component.swift
  DoBday/DoBday/View/ContentView.swift
Labels: ⚙️ Setting

#6 [Setting/#3] View 파일 추가하기
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/View/CalendarView.swift
  DoBday/DoBday/View/CreateBdayView.swift
  DoBday/DoBday/View/EditBdayView.swift
  DoBday/DoBday/View/UpComingBdayView.swift
Labels: ⚙️ Setting

#7 [PR/#4] 목업 데이터 생성
  .DS_Store
  DoBday/.DS_Store
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/Model/MockupData.swift
  DoBday/DoBday/Model/Model.swift
  DoBday/DoBday/Resource/Assets.xcassets/cinephil.imageset/Contents.json
  DoBday/DoBday/Resource/Assets.xcassets/cinephil.imageset/cinephil.jpeg
  DoBday/DoBday/Resource/Assets.xcassets/pika.imageset/Contents.json
  DoBday/DoBday/Resource/Assets.xcassets/pika.imageset/pika.png
  DoBday/DoBday/Resource/Assets.xcassets/ready.imageset/Contents.json
  DoBday/DoBday/Resource/Assets.xcassets/ready.imageset/ready.png
  DoBday/DoBday/Resource/Assets.xcassets/soy.imageset/Contents.json
  DoBday/DoBday/Resource/Assets.xcassets/soy.imageset/soy.png
Labels: ⚙️ Setting

#14 [Setting/#13] 컬러 익스텐션 추가
  .DS_Store
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/Helper/Helper+Color.swift
Labels: ⚙️ Setting

#20 [Setting/#19] info변경+helper+Fonts수정
  .DS_Store
  DoBday/.DS_Store
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/.DS_Store
  DoBday/DoBday/Helper/Helper+Fonts.swift
  DoBday/DoBday/Info.plist
  DoBday/DoBday/Resource/.DS_Store
Labels: ⚙️ Setting

#21 [Feat/#10] 데이터 추가 기능+읽기 기능 구현해보기
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/App/DoBdayApp.swift
  DoBday/DoBday/Model/Bday.swift
  DoBday/DoBday/View/CreateBdayView.swift
  DoBday/DoBday/View/UpComingBdayView.swift
Labels: 🐣 Feat

#24 [FEAT/#22] 생일 정보 삭제하기+네비게이션 이것저것
  DoBday/DoBday/View/CalendarView.swift
  DoBday/DoBday/View/UpComingBdayView.swift
Labels: 🐣 Feat

#26 [Setting/#25] 모델 수정+관계 딕셔너리 추가
  DoBday/DoBday/Model/Bday.swift
  DoBday/DoBday/View/CalendarView.swift
  DoBday/DoBday/View/CreateBdayView.swift
Labels: ⚙️ Setting

#29 [PR/#28] notiFrequency 데이터 타입 수정(String -> [String]) 및 목업 데이터 수정
  DoBday/DoBday/Model/Bday.swift
  DoBday/DoBday/Model/MockupData.swift
  DoBday/DoBday/View/CalendarView.swift
  DoBday/DoBday/View/CreateBdayView.swift
Labels: 🐣 Feat

#30 [Feat/#18] notification 구현
  .DS_Store
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/App/DoBdayApp.swift
  DoBday/DoBday/Model/Bday.swift
  DoBday/DoBday/View/LocalNotificationManager.swift
Labels: 🐣 Feat

#34 [FEAT/#27] 수정 함수 만들고 적용
  DoBday/.DS_Store
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/Helper/Helper+Date.swift
  DoBday/DoBday/Helper/Helper+ImagePicker.swift
  DoBday/DoBday/Resource/Assets.xcassets/basicprofile.imageset/Contents.json
  DoBday/DoBday/Resource/Assets.xcassets/basicprofile.imageset/default_profile.png
  DoBday/DoBday/Resource/Assets.xcassets/photologo.imageset/Contents.json
  DoBday/DoBday/Resource/Assets.xcassets/photologo.imageset/png-clipart-iphone-7-iphone-6s-computer-icons-camera-camera-angle-iphone-6-thumbnail.png
  DoBday/DoBday/View/CreateBdayView.swift
  DoBday/DoBday/View/UpComingBdayView.swift
Labels: 🐣 FEAT

#37 [FEAT] UpcomingView 및 BdayTextView
  .DS_Store
  DoBday/.DS_Store
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/View/BdayTextView.swift
  DoBday/DoBday/View/UpComingBdayView.swift
Labels: 🐣 FEAT

#38 [FEAT/#35]_피카_수정로직 짜기
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday/View/CalendarView.swift
  DoBday/DoBday/View/CreateBdayView.swift
Labels: 🐣 FEAT

#40 [FEAT/#39] 피카 캘린더뷰 삭제 기능 구현+사진 추가
  DoBday/DoBday/View/CalendarView.swift
Labels: 🐣 FEAT, 🎨 Design

#42 [FEAT/#41] 양음력구현
  DoBday/DoBday.xcodeproj/project.pbxproj
  DoBday/DoBday.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DoBday/DoBday/Model/LunarToSolarConversionView.swift
  DoBday/DoBday/View/CreateBdayView.swift
Labels: 🐣 FEAT
